package com.chronos.reportservice.controller;

import com.chronos.reportservice.dto.GeneratedReportRequestDTO;
import com.chronos.reportservice.dto.ReportResponseDTO;
import com.chronos.reportservice.service.ReportService;
import jakarta.validation.Valid;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller that manages report generation and retrieval operations.
 * <p>
 * Responsibilities:
 * - Generate new reports for managers within a specified date range.
 * - Retrieve recent reports generated by a specific manager.
 * - Retrieve recent reports for a specific team.
 * <p>
 * Base path: /api/reports
 * Security: Open endpoints for authorized users.
 * <p>
 * Created by: Sourasish Mondal
 * Since: 2025-11-06
 */

@Slf4j
@RestController
@RequestMapping("/api/reports")
public class ReportController {

    private final ReportService reportService;

    public ReportController(ReportService reportService) {
        this.reportService = reportService;
    }

    /**
     * Generate a new report for a manager within a specified date range.
     * <p>
     * HTTP: POST /api/reports/manager/{managerId}/generate
     * Security: Open endpoint.
     *
     * @param managerId the unique identifier of the manager
     * @param dto       the report generation request containing start and end dates
     * @return the generated report details
     */

    @PostMapping("/manager/{managerId}/generate")
    public ResponseEntity<ReportResponseDTO> generate(@PathVariable("managerId") String managerId, @Valid @RequestBody GeneratedReportRequestDTO dto) {
        log.info("Invoked the POST: generate controller method, managerId:{}, generateReportRequestDTO:{}", managerId, dto);
        ReportResponseDTO result = reportService.generatedReportForManager(managerId, dto.startDate(), dto.endDate());
        return new ResponseEntity<>(result, HttpStatus.CREATED);
    }

    /**
     * Retrieve recent reports generated by a specific manager.
     * <p>
     * HTTP: GET /api/reports/manager/{managerId}/recent
     * Security: Open endpoint.
     *
     * @param managerId the unique identifier of the manager
     * @return list of recent reports created by the manager
     */

    @GetMapping("/manager/{managerId}/recent")
    public ResponseEntity<List<ReportResponseDTO>> recentByManager(@PathVariable("managerId") String managerId){
        log.info("Invoked the GET: recentByManager controller method, managerId:{}", managerId);
        List<ReportResponseDTO> results = reportService.getRecentReportsForManager(managerId);
        return new ResponseEntity<>(results, HttpStatus.OK);
    }

    /**
     * Retrieve recent reports for a specific team.
     * <p>
     * HTTP: GET /api/reports/team/{teamId}/recent
     * Security: Open endpoint.
     *
     * @param teamId the unique identifier of the team
     * @return list of recent reports for the team
     */

    @GetMapping("/team/{teamId}/recent")
    public ResponseEntity<List<ReportResponseDTO>> recentByTeam(@PathVariable("teamId") String teamId) {
        log.info("Invoked the GET: recentByTeam controller method, teamId:{}", teamId);
        List<ReportResponseDTO> result = reportService.getRecentReportsForTeam(teamId);
        return new ResponseEntity<>(result, HttpStatus.OK);
    }
}
